Sites/Site/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>CV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CV</label>
        <referenceTo>CV__c</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Sites/Site/objects/CV__c.object
<CustomObject>
    <fields>
        <fullName>Additional_info__c</fullName>
        <label>Additional info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <description>Thousands  $ &apos;k&apos;</description>
        <label>Salary</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>70</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CV</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CVs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sites/Site/objects/CVJA__c.object
<CustomObject>
    <fields>
        <fullName>CV__c</fullName>
        <label>CV</label>
        <referenceTo>CV__c</referenceTo>
        <relationshipLabel>CVJAs</relationshipLabel>
        <relationshipName>CVJAs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Job_Advertisement__c</fullName>
        <label>Job Advertisement</label>
        <referenceTo>Job_Advertisement__c</referenceTo>
        <relationshipLabel>CVJAs</relationshipLabel>
        <relationshipName>CVJAs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CVJA</label>
    <nameField>
        <label>CVJobAdvertisement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CVJAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sites/Site/objects/Job_Advertisement__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>phone__c</fullName>
        <inlineHelpText>Manager&apos;s phone</inlineHelpText>
        <label>phone</label>
        <type>Phone</type>
    </fields>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CVApiHelper.cls
public class CVApiHelper {
    public static List <CVImageWrapper> getCVsWithImageIds(String offset, String limitSize){
		Integer integerOffset = Integer.valueOf(offset);   
        Integer sizeLimit = Integer.valueOf(limitSize);  
        String json;    
        DateTime yesterdayStart = Datetime.newInstance( Date.today().addDays(-8), Time.newInstance(8, 0, 0, 0) );        
        DateTime todaydaysEnd = Datetime.newInstance( Date.today(), Time.newInstance(23, 0, 0, 0) );
        
        List <CV__c> cvsResults = [SELECT Name, Status__c,Phone__c, Age__c, Email__c, CreatedDate, Salary__c , ID, Additional_info__c,
                                   (SELECT id,CV__c, Email__c, Job_Advertisement__c from CVJAs__r )
                                   FROM CV__c 
                                   WHERE CreatedDate >= :yesterdayStart AND CreatedDate <= :todaydaysEnd 
                                   ORDER BY CreatedDate LIMIT :sizeLimit OFFSET :integerOffset];
        Map <ID, CV__c> cvsMap = (new Map <ID, CV__c>(cvsResults));
        Set <ID> cvIDs = cvsMap.keySet();
        List <ContentVersion> images = [SELECT Id, CV__c FROM ContentVersion WHERE CV__c IN :cvIDs LIMIT :sizeLimit];
        List <CVImageWrapper> cvsWrapped = new List <CVImageWrapper>();
        for(ContentVersion conVer : images){
            cvsWrapped.add( new CVImageWrapper(cvsMap.get(conVer.CV__c), conVer.id) );
        }
        //Select id, LinkedEntityId, SystemModstamp from ContentDocumentLink Where ContentDocumentId IN ('0691t000000geH2AAI')
		System.debug( ' cvsWrapped.size() => ' + cvsWrapped.size() );
        return cvsWrapped;
        
    }    

    public static Integer getNewCVsCount(){
        
        DateTime yesterdayStart = Datetime.newInstance(
            Date.today().addDays(-8),
            Time.newInstance( 8, 0, 0, 0 )
        );
        DateTime todaydaysEnd  = Datetime.newInstance(
            Date.today(),
            Time.newInstance( 23, 0, 0, 0 )
        );
        
        Integer count = database.countQuery('SELECT count() from CV__c WHERE CreatedDate >= :yesterdayStart AND CreatedDate <= :todaydaysEnd ');
		System.debug( ' count => ' + count);
        return count;
    }
  
    public class CVImageWrapper{
        public String contentVersionId;
        public String email;
        public String phone;
        public String cvId;
        public Decimal age;
        public Decimal salary;
        public String name;
        public String status;
        public string additionalInfo;
        public List <ID> jobs;
        
        public CVImageWrapper( CV__c cv, Id contentVersionId ){
            this.contentVersionId = contentVersionId;
            this.phone = cv.Phone__c;
            this.email = cv.Email__c;
            this.salary = cv.Salary__c;
            this.age = cv.Age__c;
            this.name = cv.Name;
            this.cvId = cv.id;
            this.status = cv.Status__c;
            this.additionalInfo = cv.Additional_info__c;
            this.jobs = new List <ID>();
            for(CVJA__c cvja: cv.CVJAs__r){
            	jobs.add( cvja.Job_Advertisement__c );
            }            
        }
    } 
}