Sites/Site/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>CV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CV</label>
        <referenceTo>CV__c</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Sites/Site/objects/CV__c.object
<CustomObject>
    <label>CV</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CVs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sites/Site/objects/CVJA__c.object
<CustomObject>
    <fields>
        <fullName>CV__c</fullName>
        <label>CV</label>
        <referenceTo>CV__c</referenceTo>
        <relationshipLabel>CVJAs</relationshipLabel>
        <relationshipName>CVJAs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Advertisement__c</fullName>
        <label>Job Advertisement</label>
        <referenceTo>Job_Advertisement__c</referenceTo>
        <relationshipLabel>CVJAs</relationshipLabel>
        <relationshipName>CVJAs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CVJA</label>
    <nameField>
        <label>CVJobAdvertisement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CVJAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sites/Site/objects/Job_Advertisement__c.object
<CustomObject>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/JobAdvertisementTriggerHelperTest.cls
@isTest
public class JobAdvertisementTriggerHelperTest {
    @isTest
    public static void helperRemoveCVsValidTest(){
        
        List<Job_Advertisement__c> jobs = TestDataFactory.createJobAdvertisement(101);
        List < CV__c >cvs = TestDataFactory.createCVs(50);
        List < ContentVersion > conVers = TestDataFactory.createContentVersions(cvs);
        TestDataFactory.createCVJAs(cvs, jobs[0]);
        // Create 2 CV which related to 2 JobAdvertisements and should not be deleted
        TestDataFactory.createCVJAs(new List < CV__c >{cvs[0],cvs[2]}, jobs[1]);
        Test.startTest();
        JobAdvertisementTriggerHelper.removeCVs(new List < Job_Advertisement__c >{jobs[0],jobs[2]});
        Test.stopTest();
        cvs = [SELECT ID, Name FROM CV__c];
        List <CVJA__c> cvjas = [SELECT ID, Name FROM CVJA__c];
        System.assertEquals(2, cvs.size());
        System.assertEquals(2, cvs.size());
        System.debug('cvs '+ cvs.size());
    }
    
    @isTest
    public static void helperInvalidTest(){
       
        Test.startTest();
        String msg = null;
        try{
            JobAdvertisementTriggerHelper.removeCVs(null);
           
        }catch(Exception e){
            msg = e.getMessage();
        }
        Test.stopTest();
        System.assertEquals(null, msg);
    }
 
}