Sites/Site/objects/CV__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>CV</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CVs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sites/Site/objects/Job_Advertisement__c.object
<CustomObject>
    <fields>
        <fullName>email__c</fullName>
        <label>email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>phone__c</fullName>
        <inlineHelpText>Manager&apos;s phone</inlineHelpText>
        <label>phone</label>
        <type>Phone</type>
    </fields>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Task9ControllerHelperTest.cls
@isTest
public class Task9ControllerHelperTest {
	@isTest
    public static void insertCVJsInvalidTest(){
        Test.startTest();
        Map<Id, Job_Advertisement__c> jobsMap = new Map<Id, Job_Advertisement__c>();
        jobsMap.put( null, new Job_Advertisement__c());
        boolean isException = false;
        try{
            Task9ControllerHelper.insertCVJs(null, jobsMap);
        }catch(Task6Exception e ){
            isException = true;
        }      
        Test.stopTest();
        System.assert(isException);
    }
    @isTest
    public static void saveContentVersionInvalidTest(){
        Test.startTest();
        boolean isException = false;
        try{
            Task9ControllerHelper.saveContentVersion(null, null);
        }catch(Task6Exception e ){
            isException = true;
        }      
        Test.stopTest();
        System.assert(isException);
    }
    @isTest
    public static void unsuccessfulValidationCVTest(){
        CV__c cv = new CV__c( Age__c = '0', Phone__c = 'gh', Email__c= 'test' );
        boolean isException = false;
        Test.startTest();
        try{
            Task9ControllerHelper.validateCV(cv);
        }catch(Task6Exception e ){
            isException = true;
        }
        System.assert(isException);
        cv.Age__c = '25';
        try{
            Task9ControllerHelper.validateCV(cv);
        }catch(Task6Exception e ){
            isException = true;
        }
        System.assert(isException);
        cv.Email__c = 'test@test.com';
        try{
            Task9ControllerHelper.validateCV(cv);
        }catch(Task6Exception e ){
            isException = true;
        }
        System.assert(isException);
        Test.stopTest();
    }
    @isTest
    public static void insertCVInvalidTest(){
        CV__c cv = new CV__c( Age__c = '0', Phone__c = 'gh', Email__c= 'test' );
        boolean isException = false;
        Test.startTest();
        try{
            Task9ControllerHelper.insertCV(cv);
        }catch(Task6Exception e ){
            isException = true;
        }
        System.assert(isException);
    }
    @isTest
    public static void filterSelectedJobsInvalidTest(){
        
    }
}