Sites/Site/objects/CV__c.object
<CustomObject>
    <fields>
        <fullName>Additional_info__c</fullName>
        <label>Additional info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <description>Thousands  $ &apos;k&apos;</description>
        <label>Salary</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>70</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CV</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CVs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sites/Site/objects/Job_Advertisement__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>phone__c</fullName>
        <inlineHelpText>Manager&apos;s phone</inlineHelpText>
        <label>phone</label>
        <type>Phone</type>
    </fields>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Task9ControllerTest.cls
@isTest
public class Task9ControllerTest {
	@isTest
    public static void Task9ControllerUIValidTest(){
        Integer count = 101;
        List <Job_Advertisement__c> createdJobs = TestDataFactory.createDifferentJobAdvertisements( count );
        Test.startTest();
        Task9Controller tct = new Task9Controller();
        // only 71 row are not archived
        System.assertEquals( 71, tct.ssc.getResultSize() );
        //filter records by name
        tct.setNameFilter('Low');
		tct.refreshSSC();
        System.assertEquals( 31, tct.ssc.getResultSize() );
        
        List <Task9Controller.VacancyWrapper> currentPageJobs =  tct.getJobs();
        System.assertEquals( 10, currentPageJobs.size() );
        // select two records and remove one
        tct.rowIndex = 4;
        tct.doChecked();
        System.assertEquals( 1, tct.getSelectedJobs().size() );
        
        tct.rowIndex = 6;
        tct.doChecked();
        tct.rowIndex = 4;
        tct.doChecked();
        System.assertEquals( '01' , tct.getSelectedSize() );
        tct.setSize(20);
        System.assertEquals( 20 , tct.getSize() );
        
        // remove one selected record
        tct.rowIndex = 0;
        tct.removeChecked();
        System.assertEquals( '0' , tct.getSelectedSize() );
        
        // clear all filers
        tct.refresh();
        System.assertEquals( null , tct.getNameFilter() );
        //filter records by salary range
        tct.salaryFilter = 'MOREOREQUAL';
        tct.salaryParam = 100;
        tct.onSalaryFilterChange();
        for(integer i = 0; i < tct.getSize(); i++){
            tct.rowIndex = i;
            tct.doChecked();
        }
        System.assertEquals( '20' , tct.getSelectedSize() );
        
        //filter records by salary range and name
        tct.setNameFilter('High');
        tct.dateFilter = 'AFTER';
        tct.setPublishedDate(Date.today().addDays(-75));
        System.debug('tct.ssc.getResultSize() ' + tct.ssc.getResultSize());
        System.assertEquals( 15, tct.ssc.getResultSize() );
        System.assertEquals( Date.today().addDays(-75), tct.getPublishedDate() );
        System.assertEquals( 20, tct.getCheckedIDsSize() );
        Test.stopTest();
    }
    @isTest
    public static void cvSavingValidTest(){
        
        Integer count = 101;
        List <Job_Advertisement__c> createdJobs = TestDataFactory.createDifferentJobAdvertisements( count );
        Test.startTest();
        Task9Controller tct = new Task9Controller();
        tct.cvFirstName = 'FirstNameTest';
        tct.cvLastName = 'LastNameTest';
        tct.fileName = 'TestFileName';
        CV__c cv = new CV__c();
        cv.Email__c = 'test@gmail.com';
        cv.Age__c = 25;
        cv.Phone__c = '454545454243';
        cv.Salary__c = 250;
        cv.Additional_info__c = 'Test Info';
        cv.Status__c = 'true';
        tct.selectedJobs = new List <Job_Advertisement__c>{ createdJobs[0], createdJobs[1], createdJobs[2] };
        tct.image = Blob.valueOf('TestData for Image');
        tct.cv = cv ;
        tct.saveCV();
        // save again with the same List of selected Jobs
        tct.cv.Salary__c = 2500 ;
        tct.saveCV();
        Test.stopTest();
    }
    @isTest
    public static void cvSavingInvalidTest(){
        
        Integer count = 5;
        List <Job_Advertisement__c> createdJobs = TestDataFactory.createDifferentJobAdvertisements( count );
        Test.startTest();
        Task9Controller tct = new Task9Controller();
        tct.cvFirstName = 'FirstNameTest';
        tct.cvLastName = 'LastNameTest';
        tct.fileName = 'TestFileName';
        CV__c cv = new CV__c();
        cv.Email__c = 'test@gmail.com';
        cv.Age__c = 25;
        cv.Phone__c = '454545454243';
        cv.Salary__c = 250;
        cv.Additional_info__c = 'Test Info';
        cv.Status__c = 'true';
        tct.selectedJobs = new List <Job_Advertisement__c>{ createdJobs[0], createdJobs[1], createdJobs[2] };

        tct.image = null;
        tct.cv = cv ;
        tct.saveCV();
     
        tct.cv.Email__c = null;
        tct.image = Blob.valueOf('TestData for Image');
        tct.saveCV();
        
        Test.stopTest();
    }
}