Sites/Site/objects/Job_Advertisement__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_name__c</fullName>
        <label>Manager name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalaryMax__c</fullName>
        <label>SalaryMax</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalaryMin__c</fullName>
        <label>SalaryMin</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Skills_Required__c</fullName>
        <label>Skills Required</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>phone__c</fullName>
        <inlineHelpText>Manager&apos;s phone</inlineHelpText>
        <label>phone</label>
        <type>Phone</type>
    </fields>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/JobAdvertisementApiHelper.cls
global with sharing class JobAdvertisementApiHelper {
	
    
    public static String getOneJobAdvertisementAsJSON(String id){
        try{
            Job_Advertisement__c job = selectJobAdvertisementById(id);
            if( job == null ) return null;
            JobAdvertisementsWrapper wr = new JobAdvertisementsWrapper();
            String resultJSON = JSON.serialize( wr.convertToWrapper(job) );
            return resultJSON;
        }catch(Exception e ){
            throw new Task6Exception('Query exception, record was not selected !');
        }
        
    }
    public static Job_Advertisement__c selectJobAdvertisementById(String id){        
        return [SELECT id, Name, Phone__c, Location__c, Skills_Required__c,Status__c,
               Email__c,  Manager_name__c, Description__c  ,Education__c,
               SalaryMax__c, SalaryMin__c 
               FROM Job_Advertisement__c 
               where ID=:id limit 1
              ][0];         
    }
    public static void deleteJobAdvertisement(String id){
        Job_Advertisement__c obj = new Job_Advertisement__c(ID = id);
        try{
            delete obj;
        }catch(DMLException e){
            System.debug('False deleting : e ' + e );
            throw new Task6Exception('DML exception, record was not deleted !');
        }    	
    }
    public static void archivateJobAdvertisementFromJSON( String json ){
        System.debug('json archivation :  ' + json );
        try{
            LIst <String> ids = (List<String>)System.JSON.deserialize(json, List<String>.class);
            if(ids ==null || ids.isEmpty()) return;
            List <Job_Advertisement__c> jobs = new  List <Job_Advertisement__c>();
            for(String id: ids){
                jobs.add(new Job_Advertisement__c(ID = id, Status__c = 'Archived'));
                System.debug('id archivation :  ' + id );
            }
            update jobs;
        }catch(DMLException e){
            System.debug('False archivation : e ' + e );
            throw new Task6Exception('DML exception, record was not archived !');
        }catch(JSONException e){
            System.debug('False deserialization : e ' + e.getMessage() );
            throw new Task6Exception('JSON deserialization Exception');
        } 
    }
    public static String createJobAdvertisement(String str){
        try{ 
        	JobAdvertisementsWrapper modelWrapped = (JobAdvertisementsWrapper) JSON.deserialize( str, JobAdvertisementsWrapper.class);
        	Job_Advertisement__c obj = JobAdvertisementsWrapper.convertFromWrapper(modelWrapped);            
        	return insertJobAdvertisement(obj);
        }catch(JSONException e){
            System.debug('False insertion : e ' + e );
            throw new Task6Exception('JSON serialization Exception');
        }
    }
    public static String insertJobAdvertisement(Job_Advertisement__c obj){
        try{
        	insert obj;
            return obj.id;
        }catch(DMLException e){
            System.debug('DML Exception: False insertion : e ' + e );
            throw new Task6Exception('DML Exception, record was not inserted');
        }
    }
    public static void updateJobAdvertisementWithJSON(String str){
        try{
            JobAdvertisementsWrapper modelWrapped = (JobAdvertisementsWrapper)JSON.deserialize( str, JobAdvertisementsWrapper.class);
            Job_Advertisement__c model = JobAdvertisementsWrapper.convertFromWrapper(modelWrapped); 
            updateJobAdvertisement(model);        
            //return JSON.serialize(modelWrapped.convertToWrapper(resultObj));  
        }catch(JSONException e){
            System.debug('False convertion : e ' + e );
            throw new Task6Exception('JSON serialization Exception');
        }         	
    }
    public static void updateJobAdvertisement(Job_Advertisement__c obj){
        try{ 
            update obj;
        }catch(DMLException e){
            System.debug('False updating : e ' + e );
            throw new Task6Exception('DMLException ,Record with ID:' + obj.id + ' was not updated !');          
        }   
    }    
    
}