Sites/Site/objects/Job_Advertisement__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_name__c</fullName>
        <label>Manager name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalaryMax__c</fullName>
        <label>SalaryMax</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalaryMin__c</fullName>
        <label>SalaryMin</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>phone__c</fullName>
        <inlineHelpText>Manager&apos;s phone</inlineHelpText>
        <label>phone</label>
        <type>Phone</type>
    </fields>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DataFactory.cls
public class DataFactory {
	// Use this method to fill new scratch org with Test data
    public static void createJobs(){
        List <Job_Advertisement__c> jobs = new List <Job_Advertisement__c>();
            
            List <String> names = new List <String> {
                	'Java Junior', 'Java Senior ','Java Middle',' Java TeamLead' ,
                    'PHP Junior', 'PHP Senior ','PHP Middle','PHP TeamLead' ,
                    'C++ Junior', 'C++ Senior ','C++ Middle','C++ TeamLead' ,
                    'JS Junior', 'JS Senior ','JS Middle','JS TeamLead' ,
                    'Barmen', 'Dancer', 'Cleaner',
                    'Break Dancer', 'Oficiant', 'Administrator', 
                    'Manager', 'TopManager' ,'Director', 'Engineer',
                    'X-men', 'songer', 'actor' , 'saller', 'resaller', 'poet', 'driver',
                    'C# Junior', 'C# Senior ','C# Middle',
                    'Android Junior', 'Android Senior ','Android Middle','Android TeamLead' ,
                    'C++ Junior', 'C++ Senior ','C++ Middle','C++  TeamLead' ,
                    'Ruby Junior', 'Ruby Senior ','Ruby Middle','Ruby TeamLead'                     
            };
        for(Integer i = 0; i <names.size(); i++ ){
            
            jobs.add( new Job_Advertisement__c(
                Description__c ='TestDescription +',
                email__c = i +'testEmail@gmail.com' ,
                Education__c = 'high'+i,
                Location__c = 'USA',
                SalaryMax__c = 120 + i,
                SalaryMin__c = 75 - i,
                Manager_name__c = 'TestName',
                phone__c = '097654321'+ i,
                Status__c = 'Active',
                Name = names[i]
                
                
            
       		 ) ); 
        }
        insert jobs;
        
    }
}