Sites/Site/objects/Job_Advertisement__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>phone__c</fullName>
        <inlineHelpText>Manager&apos;s phone</inlineHelpText>
        <label>phone</label>
        <type>Phone</type>
    </fields>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sites/classes/JobAdvertisementsWrapperTest.cls
@isTest
public class JobAdvertisementsWrapperTest {
    @isTest
    public static void JobAdvertisementsWrapperValidTest(){        
        JobAdvertisementsWrapper obj = new JobAdvertisementsWrapper();
        Job_Advertisement__c ja = new Job_Advertisement__c(
             name = 'TestName', 
            status__c = 'Active', phone__c = '252222', email__c = 'test@test.com'
        );
        JobAdvertisementsWrapper wrappedObj = obj.convertToWrapper(ja);
        Job_Advertisement__c unwrappedObj = JobAdvertisementsWrapper.convertFromWrapper(wrappedObj);
        System.assertEquals(wrappedObj.name, unwrappedObj.name);
    }
    @isTest
    public static void JobAdvertisementsWrapperBulkValidTest(){        

        List <Job_Advertisement__c> jas = new List <Job_Advertisement__c>();
        for(Integer i = 0 ; i < 101; i++){
            Job_Advertisement__c ja = new Job_Advertisement__c(
                 name = 'TestName' + i, 
                status__c = 'Active'
            );
            jas.add(ja);
        }       
        List <JobAdvertisementsWrapper> wrappedObjs = JobAdvertisementsWrapper.convertToWrapper(jas);
        
        System.assertEquals(101, wrappedObjs.size());
        //System.assertEquals(wrappedObj.name, unwrappedObj.name);
    }
    @isTest
    public static void JobAdvertisementsWrapperInvalidTest(){        
        JobAdvertisementsWrapper obj = new JobAdvertisementsWrapper();
        Job_Advertisement__c ja = new Job_Advertisement__c( name = '' );      
        JobAdvertisementsWrapper wrappedObj = obj.convertToWrapper(ja);
        Job_Advertisement__c unwrappedObj = JobAdvertisementsWrapper.convertFromWrapper(wrappedObj);
        System.assertEquals(null, unwrappedObj);
    }
}