Sites/Site/objects/Job_Advertisement__c.object
<CustomObject>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_name__c</fullName>
        <label>Manager name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalaryMax__c</fullName>
        <label>SalaryMax</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalaryMin__c</fullName>
        <label>SalaryMin</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>On hold</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>phone__c</fullName>
        <inlineHelpText>Manager&apos;s phone</inlineHelpText>
        <label>phone</label>
        <type>Phone</type>
    </fields>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/JobsLControllerHelper.cls
public class JobsLControllerHelper {
    
    public static List <Job_Advertisement__c> getPageRecords(Map<String, String> params){
        
        String queryString = formQuery(  params);
        // String queryString = 'SELECT ID, CreatedDate from Job_Advertisement__c';
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(Database.getQueryLocator(queryString));
        ssc.setPageSize( Integer.valueOf( params.get( 'pageSize' )));
        ssc.setPageNumber(Integer.valueOf( params.get( 'pageNumber' )));
        //Integer noOfRecords = ssc.getResultSize();
        List <Job_Advertisement__c> jAs = ssc.getRecords();
        
        return jAs;
    }
    public static Integer getTotalRecordsCount( Map<String, String> params){
        System.debug('getTotalRecordsCount =>>>>');
        System.debug(params);
        String queryString = formQuery( params);
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(Database.getQueryLocator(queryString));
        Integer noOfRecords = ssc.getResultSize();
        
        return noOfRecords;
    }
	
    public static String formQuery( Map<String, String> params ){
        System.debug('params =>>>> ' + params);
        String queryString = 'Select Name,ID, Location__c, Status__c,Phone__c, Email__c,Education__c, Manager_name__c, SalaryMax__c, CreatedDate, SalaryMin__c from Job_Advertisement__c WHERE Status__c != \'Archived\'';
        List <String> paramsRows = new List <String>();
        String nameFilter = params.get('nameFilter');
        if( nameFilter != null && nameFilter != '' ){
            paramsRows.add(' Name LIKE ' + '\'%' + nameFilter + '%\'');
        }
        String publishedDateString = params.get('publishedDate');
        if(publishedDateString != '' && publishedDateString != null){
            Date publishedDate = Date.valueOf(publishedDateString);
            if(publishedDate != null && publishedDate <= System.today()){
                String dateFilter = params.get('dateFilter');
                if( dateFilter != 'ALL' || dateFilter != null || dateFilter!=''){
                    if( dateFilter == 'DAY' || dateFilter == null || dateFilter=='')paramsRows.add(' DAY_ONLY(convertTimezone(CreatedDate)) = '+ publishedDate );
                    if( dateFilter == 'BEFORE' ) paramsRows.add(' DAY_ONLY(convertTimezone(CreatedDate)) <= ' + publishedDate );
                    if( dateFilter == 'AFTER' ) paramsRows.add(' DAY_ONLY(convertTimezone(CreatedDate)) >= '+ publishedDate );
                }
            }
        }
        
        String salaryParamString = params.get('salaryParam');
        String salaryFilter = params.get('salaryFilter');
        Integer salaryParam ;
        system.debug('salaryParamString ' + salaryParamString );
        if(salaryParamString != '' && salaryParamString != null){
            salaryParam = Integer.valueOf(salaryParamString) ;
             system.debug('salaryParam ' + salaryParam );
            if(salaryParam != null && salaryParam != 0 && salaryFilter != null){
                switch on salaryFilter{
                    when 'LESS' { paramsRows.add(' SalaryMin__c < ' + salaryParam + ' '); }
                    when 'MORE' {paramsRows.add(' (SalaryMax__c > ' + salaryParam + ' OR (SalaryMin__c !=null AND SalaryMax__c = null)) ');}
                    when 'EQUAL' { paramsRows.add(' SalaryMin__c <= ' + salaryParam + ' AND (SalaryMax__c >= ' + salaryParam + ' OR SalaryMax__c = null )');}
                    when 'NOTEQUAL' {paramsRows.add(' ((SalaryMin__c > ' + salaryParam + ' OR SalaryMax__c < ' + salaryParam + ') OR SalaryMin__c = null)');}
                    when 'LESSOREQUAL' { paramsRows.add(' SalaryMin__c <= ' + salaryParam + ' '); }
                    when 'MOREOREQUAL' {
                        paramsRows.add(' (SalaryMax__c >= ' + salaryParam + ' OR (SalaryMin__c !=null AND SalaryMax__c = null)) ');
                    }
                }
            }
        }
        
        if(paramsRows != null && !paramsRows.isEmpty()){
           
                for(integer i = 0; i< paramsRows.size(); i++){
                    queryString += ' AND ' + paramsRows[i];
                }
                              
        }
        System.debug('queryString => ' + queryString);
        queryString += ' ORDER BY Name ';
        String r = '' + queryString;
        return r;
        
    }
}